"""focus — shell focus mode manager."""

import os
import pkgutil
import sys
from pathlib import Path

import click
import toml

# ── Paths ─────────────────────────────────────────────────────────────────────

CONFIG_DIR = (
    Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "zsh-focus"
)
CONFIG_FILE = CONFIG_DIR / "config.toml"
STATE_FILE = CONFIG_DIR / "state.toml"
COMPILED = CONFIG_DIR / "compiled.zsh"

# The plugin .zsh file relative to __name__
PLUGIN_FILE = "data/zsh_plugin.zsh"

# ── Config helpers ────────────────────────────────────────────────────────────


def ensure_dir():
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)


def default_config() -> dict:
    return {
        "global": {"whitelist": []},
        "settings": {
            "block_notification": True,
            "non_interactive_behavior": "block",  # "block" | "allow"
        },
        "modes": {},
    }


def load_config() -> dict:
    if not CONFIG_FILE.exists():
        return default_config()
    return toml.load(CONFIG_FILE)


def save_config(config: dict):
    ensure_dir()
    with open(CONFIG_FILE, "w") as f:
        toml.dump(config, f)


def load_state() -> dict:
    if not STATE_FILE.exists():
        return {"active_mode": ""}
    return toml.load(STATE_FILE)


def save_state(state: dict):
    ensure_dir()
    with open(STATE_FILE, "w") as f:
        toml.dump(state, f)


def expand(p: str) -> str:
    """Expand ~ and resolve to absolute path."""
    return str(Path(p).expanduser().resolve())


# ── Compiler ──────────────────────────────────────────────────────────────────


def compile_zsh(config: dict, state: dict):
    """Write compiled.zsh from current config + state."""
    settings = config.get("settings", {})
    active_mode = state.get("active_mode", "")
    block_notif = "true" if settings.get("block_notification", True) else "false"
    non_interact = settings.get("non_interactive_behavior", "block")

    global_wl = [expand(p) for p in config.get("global", {}).get("whitelist", [])]

    mode_wl: list[str] = []
    mode_bl: list[str] = []
    if active_mode and active_mode in config.get("modes", {}):
        mc = config["modes"][active_mode]
        mode_wl = [expand(p) for p in mc.get("whitelist", [])]
        mode_bl = [expand(p) for p in mc.get("blacklist", [])]

    def zsh_array(items: list[str]) -> str:
        return "(" + " ".join(f'"{i}"' for i in items) + ")"

    lines = [
        "# Auto-generated by focus CLI — do not edit manually",
        f'ZSH_FOCUS_ACTIVE_MODE="{active_mode}"',
        f'ZSH_FOCUS_BLOCK_NOTIFICATION="{block_notif}"',
        f'ZSH_FOCUS_NON_INTERACTIVE="{non_interact}"',
        f"ZSH_FOCUS_GLOBAL_WHITELIST={zsh_array(global_wl)}",
        f"ZSH_FOCUS_MODE_WHITELIST={zsh_array(mode_wl)}",
        f"ZSH_FOCUS_MODE_BLACKLIST={zsh_array(mode_bl)}",
    ]

    ensure_dir()
    COMPILED.write_text("\n".join(lines) + "\n")


# ── CLI ───────────────────────────────────────────────────────────────────────


@click.group()
def cli():
    """Focus mode manager — keep your shell sessions intentional."""
    pass


@cli.command(name="init")
@click.option(
    "--cmd",
    default=None,
    metavar="NAME",
    help="The command name passed to zoxide init (e.g. --cmd cd). "
    "Omit if you didn't pass --cmd to zoxide.",
)
def init_zsh(cmd):
    """Print zsh integration. Add to .zshrc: eval "$(focus init zsh)"

    If you initialise zoxide with a custom command name, mirror it here:

      eval "$(zoxide init zsh --cmd cd)"
      eval "$(focus init zsh --cmd cd)"
    """
    data = pkgutil.get_data(__name__, PLUGIN_FILE)

    if not data:
        raise click.ClickException(
            f"Couldn't find packaged file {PLUGIN_FILE}."
            "Contact the developer. This should not happen."
        )

    # Ensure the compiled cache exists so the first source doesn't fail silently
    if not COMPILED.exists():
        config = load_config()
        state = load_state()
        compile_zsh(config, state)

    zoxide_cmd = cmd if cmd else "z"
    click.echo(f'_FOCUS_ZOXIDE_CMD="{zoxide_cmd}"')
    click.echo(data.decode())


@cli.command()
@click.argument("mode")
def on(mode):
    """Activate a focus mode."""
    config = load_config()
    if mode not in config.get("modes", {}):
        click.echo(
            f"Error: mode '{mode}' doesn't exist. Create it with:\n"
            f"  focus new {mode}",
            err=True,
        )
        sys.exit(1)
    state = {"active_mode": mode}
    save_state(state)
    compile_zsh(config, state)
    click.echo(f"✓ Focus mode '{mode}' activated.")


@cli.command()
def off():
    """Deactivate focus mode (transparent shell)."""
    config = load_config()
    state = {"active_mode": ""}
    save_state(state)
    compile_zsh(config, state)
    click.echo("✓ Focus mode deactivated.")


@cli.command()
def status():
    """Show active mode and directory lists."""
    config = load_config()
    state = load_state()
    active = state.get("active_mode", "")

    if active:
        click.echo(f"Active mode: {click.style(active, bold=True)}")
        mc = config.get("modes", {}).get(active, {})
        for label, key in (("  Whitelist", "whitelist"), ("  Blacklist", "blacklist")):
            entries = mc.get(key, [])
            if entries:
                click.echo(f"{label}:")
                for e in entries:
                    click.echo(f"    {e}")
    else:
        click.echo("No active focus mode.")

    global_wl = config.get("global", {}).get("whitelist", [])
    if global_wl:
        click.echo("Global whitelist:")
        for e in global_wl:
            click.echo(f"  {e}")

    settings = config.get("settings", {})
    click.echo("\nSettings:")
    click.echo(
        f"  block_notification:       {settings.get('block_notification', True)}"
    )
    click.echo(
        f"  non_interactive_behavior: {settings.get('non_interactive_behavior', 'block')}"
    )


@cli.command(name="new")
@click.argument("mode")
def new_mode(mode):
    """Create a new focus mode."""
    config = load_config()
    config.setdefault("modes", {})
    if mode in config["modes"]:
        click.echo(f"Mode '{mode}' already exists.")
        return
    config["modes"][mode] = {"whitelist": [], "blacklist": []}
    save_config(config)
    click.echo(f"✓ Mode '{mode}' created.")


@cli.command(name="list")
def list_modes():
    """List all focus modes."""
    config = load_config()
    state = load_state()
    active = state.get("active_mode", "")
    modes = config.get("modes", {})

    if not modes:
        click.echo("No modes yet. Create one with: focus new <mode>")
        return

    for name, mc in modes.items():
        marker = click.style(" ◀ active", fg="green") if name == active else ""
        wl_count = len(mc.get("whitelist", []))
        bl_count = len(mc.get("blacklist", []))
        click.echo(f"  {name}{marker}  (allow: {wl_count}, deny: {bl_count})")


@cli.command()
@click.argument("path", default="")
@click.option(
    "-m", "--mode", default=None, help="Mode to add to (default: global whitelist)"
)
def allow(path, mode):
    """
    Whitelist a directory. Defaults to current directory.

    Without -m, adds to the global whitelist (all modes).
    With -m <mode>, adds to that mode's whitelist.
    """
    target = expand(path) if path else os.getcwd()
    config = load_config()
    state = load_state()

    if mode is None:
        wl = config.setdefault("global", {}).setdefault("whitelist", [])
        if target in wl:
            click.echo(f"'{target}' is already in the global whitelist.")
            return
        wl.append(target)
        save_config(config)
        compile_zsh(config, state)
        click.echo(f"✓ '{target}' → global whitelist")
    else:
        if mode not in config.get("modes", {}):
            click.echo(f"Error: mode '{mode}' doesn't exist.", err=True)
            sys.exit(1)
        wl = config["modes"][mode].setdefault("whitelist", [])
        if target in wl:
            click.echo(f"'{target}' is already in '{mode}' whitelist.")
            return
        wl.append(target)
        save_config(config)
        compile_zsh(config, state)
        click.echo(f"✓ '{target}' → mode '{mode}' whitelist")


@cli.command()
@click.argument("path", default="")
@click.option("-m", "--mode", required=True, help="Mode to add the deny rule to")
def deny(path, mode):
    """
    Blacklist a directory. Defaults to current directory.

    Always requires -m <mode> (blacklists are per-mode, never global).
    """
    target = expand(path) if path else os.getcwd()
    config = load_config()
    state = load_state()

    if mode not in config.get("modes", {}):
        click.echo(f"Error: mode '{mode}' doesn't exist.", err=True)
        sys.exit(1)

    bl = config["modes"][mode].setdefault("blacklist", [])
    if target in bl:
        click.echo(f"'{target}' is already in '{mode}' blacklist.")
        return
    bl.append(target)
    save_config(config)
    compile_zsh(config, state)
    click.echo(f"✓ '{target}' → mode '{mode}' blacklist")


@cli.command()
@click.argument("path", default="")
@click.option(
    "-m", "--mode", default=None, help="Mode to remove from (default: global)"
)
def remove(path, mode):
    """
    Remove a whitelist or blacklist entry. Defaults to current directory.

    Without -m, removes from the global whitelist.
    With -m <mode>, removes from that mode's whitelist and/or blacklist.
    """
    target = expand(path) if path else os.getcwd()
    config = load_config()
    state = load_state()
    removed = False

    if mode is None:
        wl = config.get("global", {}).get("whitelist", [])
        if target in wl:
            wl.remove(target)
            removed = True
            click.echo(f"✓ Removed '{target}' from global whitelist.")
    else:
        if mode not in config.get("modes", {}):
            click.echo(f"Error: mode '{mode}' doesn't exist.", err=True)
            sys.exit(1)
        mc = config["modes"][mode]
        for list_name in ("whitelist", "blacklist"):
            lst = mc.get(list_name, [])
            if target in lst:
                lst.remove(target)
                removed = True
                click.echo(f"✓ Removed '{target}' from mode '{mode}' {list_name}.")

    if removed:
        save_config(config)
        compile_zsh(config, state)
    else:
        click.echo(f"'{target}' wasn't found in any list.")


