"""Compile config + state into a sourced zsh variable file."""

from pathlib import Path

from zsh_focus.config import COMPILED, Config, State, ensure_dir, expand


def compile_zsh(config: Config, state: State) -> None:
    """Write compiled.zsh from current config + state."""
    active_mode = state.active_mode
    block_notif = "true" if config["settings"]["block_notification"] else "false"
    non_interact = config["settings"]["non_interactive_behavior"]

    global_wl: list[Path] = [expand(p) for p in config["always"]["whitelist"]]

    mode_strict = False
    mode_wl: list[Path] = []
    mode_bl: list[Path] = []
    if active_mode and active_mode in config["modes"]:
        mc = config["modes"][active_mode]
        mode_strict = mc["strict"]
        mode_wl = [expand(p) for p in mc["whitelist"]]
        mode_bl = [expand(p) for p in mc["blacklist"]]

    def zsh_array(items: list[Path]) -> str:
        return "(" + " ".join(f'"{i}"' for i in items) + ")"

    strict = "true" if mode_strict else "false"

    lines = [
        "# Auto-generated by zsh-focus CLI — do not edit manually",
        f'ZSH_FOCUS_ACTIVE_MODE="{active_mode}"',
        f'ZSH_FOCUS_BLOCK_NOTIFICATION="{block_notif}"',
        f'ZSH_FOCUS_NON_INTERACTIVE="{non_interact}"',
        f'ZSH_FOCUS_STRICT="{strict}"',
        f"ZSH_FOCUS_GLOBAL_WHITELIST={zsh_array(global_wl)}",
        f"ZSH_FOCUS_MODE_WHITELIST={zsh_array(mode_wl)}",
        f"ZSH_FOCUS_MODE_BLACKLIST={zsh_array(mode_bl)}",
    ]

    ensure_dir()
    COMPILED.write_text("\n".join(lines) + "\n")
