"""Compile config + state into a sourced zsh variable file."""

from .config import COMPILED, ensure_dir, expand


def compile_zsh(config: dict, state: dict):
    """Write compiled.zsh from current config + state."""
    settings = config.get("settings", {})
    active_mode = state.get("active_mode", "")
    block_notif = "true" if settings.get("block_notification", True) else "false"
    non_interact = settings.get("non_interactive_behavior", "block")

    global_wl = [expand(p) for p in config.get("global", {}).get("whitelist", [])]

    mode_wl: list[str] = []
    mode_bl: list[str] = []
    if active_mode and active_mode in config.get("modes", {}):
        mc = config["modes"][active_mode]
        mode_wl = [expand(p) for p in mc.get("whitelist", [])]
        mode_bl = [expand(p) for p in mc.get("blacklist", [])]

    def zsh_array(items: list[str]) -> str:
        return "(" + " ".join(f'"{i}"' for i in items) + ")"

    lines = [
        "# Auto-generated by focus CLI — do not edit manually",
        f'ZSH_FOCUS_ACTIVE_MODE="{active_mode}"',
        f'ZSH_FOCUS_BLOCK_NOTIFICATION="{block_notif}"',
        f'ZSH_FOCUS_NON_INTERACTIVE="{non_interact}"',
        f"ZSH_FOCUS_GLOBAL_WHITELIST={zsh_array(global_wl)}",
        f"ZSH_FOCUS_MODE_WHITELIST={zsh_array(mode_wl)}",
        f"ZSH_FOCUS_MODE_BLACKLIST={zsh_array(mode_bl)}",
    ]

    ensure_dir()
    COMPILED.write_text("\n".join(lines) + "\n")
