"""Focus mode engine — compile config to shell variables and evaluate path decisions."""

from pathlib import Path
from typing import Literal

from zsh_focus.config import COMPILED, ensure_dir, expand
from zsh_focus.types import CheckResult, Config, MatchedEntry, Source, State

# ── Path check (mirrors _focus_check_dir in zsh) ──────────────────────────────


def check_path(config: Config, state: State, target: Path) -> CheckResult:
    """Evaluate target against the active mode's lists and return a structured result.

    Mirrors _focus_check_dir in the zsh plugin: all entries from the always
    whitelist, mode whitelist, mode blacklist, and mode warnlist are tested as
    path prefixes.  The longest matching entry wins; ties: black ≥ warn > white.
    Unmatched paths are always allowed.
    """
    active_mode = state.active_mode

    if not active_mode:
        return CheckResult(
            target=target,
            active_mode="",
            matched=[],
            verdict="allow",
        )

    mc = config["modes"].get(active_mode)

    # Collect all candidates: (resolved_entry, source_label)
    candidates: list[tuple[Path, Source]] = []
    for p in config["always"]["whitelist"]:
        candidates.append((expand(p), "always whitelist"))
    if mc:
        for p in mc["whitelist"]:
            candidates.append((expand(p), "mode whitelist"))
        for p in mc["blacklist"]:
            candidates.append((expand(p), "mode blacklist"))
        for p in mc["warnlist"]:
            candidates.append((expand(p), "mode warnlist"))

    # Find all entries that are a prefix of (or equal to) the target
    matched: list[MatchedEntry] = []
    best_white: Path | None = None
    best_black: Path | None = None
    best_warn: Path | None = None

    for entry, source in candidates:
        if target.is_relative_to(entry):
            matched.append(MatchedEntry(entry=entry, source=source))
            if source == "mode blacklist":
                if best_black is None or len(str(entry)) > len(str(best_black)):
                    best_black = entry
            elif source == "mode warnlist":
                if best_warn is None or len(str(entry)) > len(str(best_warn)):
                    best_warn = entry
            else:
                if best_white is None or len(str(entry)) > len(str(best_white)):
                    best_white = entry

    # Determine verdict — longest wins; ties: black ≥ warn > white.
    # Iterate lowest→highest priority with >=, so higher priority wins on equal length.
    verdict: Literal["allow", "block", "prompt"] = "allow"
    winner: Path | None = None
    if best_white or best_black or best_warn:
        best_len = -1
        pairs: list[tuple[Path | None, Literal["allow", "block", "prompt"]]] = [
            (best_white, "allow"),
            (best_warn, "prompt"),
            (best_black, "block"),
        ]
        for candidate, v in pairs:
            if candidate is not None and len(str(candidate)) >= best_len:
                best_len = len(str(candidate))
                verdict = v
                winner = candidate

    for m in matched:
        if m.entry == winner:
            m.is_winner = True

    # Most specific first
    matched.sort(key=lambda m: len(str(m.entry)), reverse=True)

    return CheckResult(
        target=target,
        active_mode=active_mode,
        matched=matched,
        verdict=verdict,
    )


# ── Compiler ──────────────────────────────────────────────────────────────────


def compile_zsh(config: Config, state: State) -> None:
    """Write COMPILED from the current config and state.

    The file is sourced by the zsh precmd hook on every prompt; it exports
    shell variables that drive the focus enforcement logic without requiring
    a Python call on each directory change.
    """
    active_mode = state.active_mode
    block_notif = "true" if config["settings"]["block_notification"] else "false"
    non_interact = config["settings"]["non_interactive_behavior"]

    global_wl: list[Path] = [expand(p) for p in config["always"]["whitelist"]]

    mode_wl: list[Path] = []
    mode_bl: list[Path] = []
    mode_warn: list[Path] = []
    if active_mode and active_mode in config["modes"]:
        mc = config["modes"][active_mode]
        mode_wl = [expand(p) for p in mc["whitelist"]]
        mode_bl = [expand(p) for p in mc["blacklist"]]
        mode_warn = [expand(p) for p in mc["warnlist"]]

    def zsh_array(items: list[Path]) -> str:
        return "(" + " ".join(f'"{i}"' for i in items) + ")"

    lines = [
        "# Auto-generated by zsh-focus CLI — do not edit manually",
        f'ZSH_FOCUS_ACTIVE_MODE="{active_mode}"',
        f'ZSH_FOCUS_BLOCK_NOTIFICATION="{block_notif}"',
        f'ZSH_FOCUS_NON_INTERACTIVE="{non_interact}"',
        f"ZSH_FOCUS_GLOBAL_WHITELIST={zsh_array(global_wl)}",
        f"ZSH_FOCUS_MODE_WHITELIST={zsh_array(mode_wl)}",
        f"ZSH_FOCUS_MODE_BLACKLIST={zsh_array(mode_bl)}",
        f"ZSH_FOCUS_MODE_WARNLIST={zsh_array(mode_warn)}",
    ]

    ensure_dir()
    COMPILED.write_text("\n".join(lines) + "\n")
